apiVersion: "jonasg.be/v1"
kind: Application
metadata:
  name: test
spec:
  app: test
  environments:
    - ci
    - dev
    - uat
    - prd
  quota:
     - env: "ci"
       requests:
         cpu: "1"
         memory: "1"
         ephemeral-storage: "1"
       limits:
         cpu: "4"
         memory: "4"
         ephemeral-storage: "1"
     - env: "dev"
       requests:
         cpu: "1"
         memory: "1"
         ephemeral-storage: "1"
       limits:
         cpu: "4"
         memory: "4"
         ephemeral-storage: "1"
     - env: "uat"
       requests:
         cpu: "1"
         memory: "1"
         ephemeral-storage: "1"
       limits:
         cpu: "4"
         memory: "4"
         ephemeral-storage: "1"
     - env: "prd"
       requests:
         cpu: "1"
         memory: "1"
         ephemeral-storage: "1"
       limits:
         cpu: "4"
         memory: "4"
         ephemeral-storage: "1"
  defaultNetworkPolicies: true
  pullSecret: '{"auths":{"test":{"auth":"test"}}}'
