apiVersion: apps/v1
kind: Deployment
metadata:
  name: application-operator
  namespace: operators
  labels:
    app: application-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: application-operator
  template:
    metadata:
      labels:
        app: application-operator
    spec:
      containers:
      - name: application-operator
        image: docker.io/govaertsjonas/application-operator:dev
        imagePullPolicy: IfNotPresent
      serviceAccountName: application-operator
